 ### <center>NumPy Basics</center>
 
     This notebook gives an overview of basic concepts of NumPy.
     The topics covered in this notebook are as follows:
     
     1. NumPy Installation
     
         - Installation Instructions
         - Using alias
     
     2. NumPy Array Creation
 
         - Creating NumPy array from a Python List
         - Creating NumPy array from Built-in routines
         - Creating NumPy array using np.random
     
     3. NumPy Array Attributes
    
         - Dimension
         - Size
         - Shape
         - Memory consumption
         - Datatype
         - Itemsize
    
     4. NumPy Array Manipulation
 
         - Array Indexing : Accessing Single elements
         - Array Slicing : Accessing Subarrays
         - Creating Copies of Arrays
         - Reshaping Arrays
             > Transposing arrays
             > Swapping axes
         - Raveling/Flattening
         - Concatenating Arrays
         - Splitting one array to many
         - Repeating Elements
             > tile method
             > repeat method

### <center> NumPy Installation </center> 

        Before you can start with this tutorial, you need to make sure of the "version" of the numpy installed.
    
> #### Installation Instructions:

    1. Mac and Linux users can install NumPy via pip command:
    
    pip install numpy
    
    2. Windows does not have any package manager analogous to that in linux or mac.
    Please download the pre-built windows installer for NumPy from here (according to your system configuration and 
    Python version).
    And then install the packages manually.   
    
    3. For more detailed instructions, you could also go to the NumPy website and follow the installation 
       instructions found there. 
       These are general instructions for installing packages in the SciPy ecosystem.

        https://scipy.org/install.html 

> #### Using alias : 
   
     By convention, you’ll find that most people in the SciPy/PyData world will import NumPy using np as an alias:
     
     import numpy as np
     
     Once you have the Python library already available,you could just double-check the version after importing the 
     numpy library using this command:
    
     np.__version__
     
> #### This tutorial uses numpy version "1.16". 


In [104]:
# Importing numpy using np as alias
import numpy as np

In [105]:
np.__version__

'1.16.2'

### <center> Creating NumPy Arrays </center> 

        We can use np.array() to create arrays from other python structures like lists or tuples. If we do not 
    mention the dtype when creating an array, NumPy tries to guess the dtype for the array. However, its a good 
    practice to explicitly mention dtype when creating an array to avoid unexpected casting of the dtype.
    
    NumPy supports a diverse set of numerical types than Python. The standard ones include bool, int_, intc, 
    intp, int8, int16, int 32, int64, uint8, uint16, uint32, uint64, float_, float16, float32, float64, complex_, 
    complex64, complex128.
    
    Please Note :
    1. NumPy will upcast if the types of elements in the array do not match.
    2. For a detailed discussion on the data-types supported by NumPy,refer NumPy Documentation.
       https://docs.scipy.org/doc/numpy/user/basics.types.html
    

> #### Creating NumPy array from a Python List/tuple

In [106]:
# Creating a simple array from a nested list of type int
arr_number_list = np.array([[[1,2,3],
                             [4,5,6],
                             (7,8,9)],
                            [[1,2,3],
                             (4,5,6),
                             [7,8,9]]],dtype="int32")

print(f"Array created from a nested list of int type  :\n\n {arr_number_list}")

Array created from a nested list of int type  :

 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [107]:
# Creating an array from a nested list of unicode type
arr_unicode_list=np.array([[["chrome","safari","firefox"],
                            ["opera","edge","ie"],
                            ["tor","brave","chromium"]],
              
                           [["Kodiak","Cheetah","Puma"],
                            ["Jaguar","Panther","Tiger"],
                            ["Leopard","Snow Leopard","Lion"]],
             
                           [["Mountain Lion","Mavericks","Yosemite"],
                            ["EI Captain","Sierra","High Sierra"],
                            ["Mojave","Catalina","Apple"]]])

print(f"Array created from a nested list of Unicode type  :\n\n {arr_unicode_list}")

Array created from a nested list of Unicode type  :

 [[['chrome' 'safari' 'firefox']
  ['opera' 'edge' 'ie']
  ['tor' 'brave' 'chromium']]

 [['Kodiak' 'Cheetah' 'Puma']
  ['Jaguar' 'Panther' 'Tiger']
  ['Leopard' 'Snow Leopard' 'Lion']]

 [['Mountain Lion' 'Mavericks' 'Yosemite']
  ['EI Captain' 'Sierra' 'High Sierra']
  ['Mojave' 'Catalina' 'Apple']]]


> #### Creating NumPy array from Built-in routines

        There is another efficient way to create arrays as they grow larger in size. This is achieved by using 
    intrinsic numpy array creation objects like np.arange(), np.ones(), np.zeros(), np.empty(), np.full(), 
    np.eye() and np.linspace()
        
 

In [108]:
# Creating larger arrays with built-in routines

# Creating floating-point array filled with 1s
print("\n Array of Ones : ")
print (np.ones(35,dtype=float))

# Creating integer array filled with 0s
print("\n Array of zeros : ")
print(np.zeros(20,dtype=int))

# Creating array filled with any element 
print("\n Array with same element : ")
print(np.full((4,4),0.99))


 Array of Ones : 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

 Array of zeros : 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 Array with same element : 
[[0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99]
 [0.99 0.99 0.99 0.99]]


In [109]:
# Creating arrays with sequences

# Starting at 0, Ending at 22, stepping by 3
print("Using np.arange between 0 and 22 with steps of 3: np.arange(start,end,step) ")
print(np.arange(0,22,3))

# Creating an array with 4 evenly spaced values between 0 and 10
print("\nUsing np.linspace to create 4 evenly spaced entries between 0 and 10 : np.linspace(start,end,spacing) ")
print(np.linspace(0,10,4))

# Creating an identity matrix
print("\n4x4 Identity matrix : np.eye ")
print(np.eye(4))

# Creating an empty matrix
print("\nUnititalized matrix : np.empty ")
print(np.empty((8),dtype=int))

Using np.arange between 0 and 22 with steps of 3: np.arange(start,end,step) 
[ 0  3  6  9 12 15 18 21]

Using np.linspace to create 4 evenly spaced entries between 0 and 10 : np.linspace(start,end,spacing) 
[ 0.          3.33333333  6.66666667 10.        ]

4x4 Identity matrix : np.eye 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Unititalized matrix : np.empty 
[ 0  3  6  9 12 15 18 21]


> #### Creating NumPy array using np.random and np.diagonal

        There are special libraries that can be used to create arrays for specific purposes. The most commonly used 
    are the array generation functions in np.random module that can generate arrays of random values, and some 
    utility functions to generate special matrices (e.g. diagonal).

    We shall discuss np.random() and np.diagonal() with examples.
    

In [110]:
# Creating an array with random values
print(f"\nRandom array with float :\n\n{np.random.randn(4,3)}")


Random array with float :

[[ 0.61367588 -0.44783953 -1.56709178]
 [ 0.30657043 -0.10522764  0.16227432]
 [ 1.99169311  0.06694193 -0.22029842]
 [-0.38237301 -0.02669823  0.97186742]]


In [111]:
# Creating an array with normally distributed random values
print(f"Normally distributed random array with a Mean of 10 and a Standard Deviation of 4 :\n\n {np.random.normal(10,4,(3,3))}")

Normally distributed random array with a Mean of 10 and a Standard Deviation of 4 :

 [[ 9.9162497  14.28521242  7.3724429 ]
 [11.78584991  7.28918487 10.89974951]
 [ 8.83757607 12.69781965 11.3450938 ]]


In [112]:
# Creatin random array with integers in a given interval
print(f"Creating a 3x4 array with random values in the interval 2 to 10 :\n\n{np.random.randint(2,10,(3,4))}")

Creating a 3x4 array with random values in the interval 2 to 10 :

[[4 5 8 4]
 [9 3 5 3]
 [8 2 6 4]]


In [113]:
# np.diagonal returns specified diagonals from the array
arr_diagonal = np.arange(48).reshape(4,3,4)
print(f'Original array :\n {arr_diagonal}')

# Offsets main diagonal by 1; Constructs an array with axis 2 and axis 0 and gets diagonal elements
print(f'\nDiagonal array :\n\n{arr_diagonal.diagonal(1,2,0)} ')

Original array :
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

Diagonal array :

[[12 25 38]
 [16 29 42]
 [20 33 46]] 


### <center> NumPy Array Attributes </center> 

> #### Size of NumPy Arrays

    Dimension
    Size
    Shape
    nbytes
    dtype
    itemsize

In [114]:
# We create a 1D, 2D and a 3D array to explore the attributes
# One-Dimensional Array
one_dim_array = np.random.randint(12, size=7)

# Two-Dimensional Array
two_dim_array = np.array([["Cupcake","Donut"],
                   ["Eclair","Froyo"],
                   ["Gingerbread","Honeycomb"],
                   ["Ice Cream Sandwich","Jelly Bean"],
                   ["KitKat","Lollipop"],
                   ["Marshmallow","Nougat"],
                   ["Oreo","Pie"]])

# Three-Dimensional Array
three_dim_array = np.array([[["Civic","Accord","Pilot","FR-V"],
                       ["Odyssey","Jazz","CR-V","NSX"]],
                      [["Insight","Ridgeline","Legend","HR-V"],
                       ["Passport","S660","Clarity","Mobilio"]],
                      [["Airwave","Avancier","Beat","Shuttle"],
                       ["Concerto","Element","Logo","Stream"]]])

In [115]:
# Arrays created
print("One-Dimensional Array :\n\n{}".format(one_dim_array))
print("\nTwo-Dimensional Array :\n\n{}".format(two_dim_array))
print("\nThree-Dimensional Array : 3 sheets, 2 Rows, 4 Columns \n\n{}".format(three_dim_array))

One-Dimensional Array :

[ 4 11  8  8  5  5  2]

Two-Dimensional Array :

[['Cupcake' 'Donut']
 ['Eclair' 'Froyo']
 ['Gingerbread' 'Honeycomb']
 ['Ice Cream Sandwich' 'Jelly Bean']
 ['KitKat' 'Lollipop']
 ['Marshmallow' 'Nougat']
 ['Oreo' 'Pie']]

Three-Dimensional Array : 3 sheets, 2 Rows, 4 Columns 

[[['Civic' 'Accord' 'Pilot' 'FR-V']
  ['Odyssey' 'Jazz' 'CR-V' 'NSX']]

 [['Insight' 'Ridgeline' 'Legend' 'HR-V']
  ['Passport' 'S660' 'Clarity' 'Mobilio']]

 [['Airwave' 'Avancier' 'Beat' 'Shuttle']
  ['Concerto' 'Element' 'Logo' 'Stream']]]


##### Dimension

In [116]:
# The ndim attribute returns the dimension of the array
print("Dimension of one-dimensional array: {}".format(one_dim_array.ndim))
print("Dimension of two-dimensional array: {}".format(two_dim_array.ndim))
print("Dimension of three-dimensional array: {}".format(three_dim_array.ndim))

Dimension of one-dimensional array: 1
Dimension of two-dimensional array: 2
Dimension of three-dimensional array: 3


##### Size

In [117]:
# The size attribute returns the number of elements in the array
print("Size of one-dimensional array: {}".format(one_dim_array.size))
print("Size of two-dimensional array: {}".format(two_dim_array.size))
print("Size of three-dimensional array: {}".format(three_dim_array.size))

Size of one-dimensional array: 7
Size of two-dimensional array: 14
Size of three-dimensional array: 24


##### Shape

In [118]:
# The shape attribute returns a tuple of array-dimensions
print("Shape of one-dimensional array: {}".format(one_dim_array.shape))
print("Shape of two-dimensional array: {}".format(two_dim_array.shape))
print("Shape of three-dimensional array: {}".format(three_dim_array.shape))

Shape of one-dimensional array: (7,)
Shape of two-dimensional array: (7, 2)
Shape of three-dimensional array: (3, 2, 4)


##### nbytes

In [119]:
# The nbytes attribute returns the total bytes consumed by the elements of the array
print("Number of bytes of one-dimensional array: {}".format(one_dim_array.nbytes))
print("Number of bytes of two-dimensional array: {}".format(two_dim_array.nbytes))
print("Number of bytes of three-dimensional array: {}".format(three_dim_array.nbytes))

Number of bytes of one-dimensional array: 56
Number of bytes of two-dimensional array: 1008
Number of bytes of three-dimensional array: 864


##### dtype

In [120]:
# The dtype attribute returns the data-type of the array elements
print("Dtype of one-dimensional array: {}".format(one_dim_array.dtype))
print("Dtype of two-dimensional array: {}".format(two_dim_array.dtype))
print("Dtype of three-dimensional array: {}".format(three_dim_array.dtype))

Dtype of one-dimensional array: int64
Dtype of two-dimensional array: <U18
Dtype of three-dimensional array: <U9


##### itemsize

In [121]:
# The itemsize attribute returns the length of one array element in bytes.
print("\n Itemsize of one-dimensional array:{}".format(one_dim_array.itemsize))
print("\n Itemsize of two-dimensional array: {}".format(two_dim_array.itemsize))
print("\n Itemsize of three-dimensional array:{}".format(three_dim_array.itemsize))


 Itemsize of one-dimensional array:8

 Itemsize of two-dimensional array: 72

 Itemsize of three-dimensional array:36


### <center> NumPy Array Manipulation</center> 

> #### Array Indexing

    We shall now discuss simple array indexing (i.e. to get single values from arrays and to set single values in 
    arrays)

In [123]:
# Array Indexing on a One-dimensional array
print(f"\n {one_dim_array}")

# Accessing the 3rd element in the array
print("\nSecond element in the array is {}".format(one_dim_array[2]))
# Alternate way
print("\nUsing negative indices : Second element in the array is {}".format(one_dim_array[-5]))

# Setting 5th element of array : If a FLOAT VALUE is set, it will be truncated since this is a integer array
one_dim_array[4]= 49.96
print("\nFifth element in the array is set to {}".format(one_dim_array[4]))


 [ 4 11  8  8  5  5  2]

Second element in the array is 8

Using negative indices : Second element in the array is 8

Fifth element in the array is set to 49


In [124]:
# Array Indexing on a Two-dimensional array
print(f"\n {two_dim_array}")

# Accessing the 2nd element in the second row
print("\nSecond element in the second row of this array is {}".format(two_dim_array[1,1]))
# Alternate way
print("\nUsing Negative Indicies : Second element in the second row of this array is {}".format(two_dim_array[-6,-1]))


# Setting 1st element of 3rd row of the array ; 
# Since the array is created with limit of characters as 18; The string is truncated above 18
two_dim_array[2,0]="GingerBread Android"
print("\nFirst element in the third row of this array is {}".format(two_dim_array[2,0]))



 [['Cupcake' 'Donut']
 ['Eclair' 'Froyo']
 ['Gingerbread' 'Honeycomb']
 ['Ice Cream Sandwich' 'Jelly Bean']
 ['KitKat' 'Lollipop']
 ['Marshmallow' 'Nougat']
 ['Oreo' 'Pie']]

Second element in the second row of this array is Froyo

Using Negative Indicies : Second element in the second row of this array is Froyo

First element in the third row of this array is GingerBread Androi


In [134]:
# Array Indexing on a Three-dimensional array
print(f"\n {three_dim_array}")

# Accessing the element in the 1st sheet, 2nd row and 4th column : NSX 
print("\nSecond element in the second row of this array is {}".format(three_dim_array[0,1,3]))
# Alternate way
print("\nUsing Negative Indicies : Second element in the second row of this array is {}".format(three_dim_array[-3,-1,-1]))


# Setting 1st element of 3rd sheet of the array ; 
three_dim_array[2,0,0]="Fit"
print("\nFirst element in the last sheet of this array is {}".format(three_dim_array[2,0,0]))



 [[['Civic' 'Accord' 'Pilot' 'FR-V']
  ['Odyssey' 'Jazz' 'CR-V' 'NSX']]

 [['Insight' 'Ridgeline' 'Legend' 'HR-V']
  ['Passport' 'S660' 'Clarity' 'Mobilio']]

 [['Airwave' 'Avancier' 'Beat' 'Shuttle']
  ['Concerto' 'Element' 'Logo' 'Stream']]]

Second element in the second row of this array is NSX

Using Negative Indicies : Second element in the second row of this array is NSX

First element in the last sheet of this array is Fit


> #### Array Slicing
    
    To access multiple elements as a slice of an array, we use array[start:stop:step]
    (Example : If none is specified arr[:15] defaults to start=0, stop =15 and step=1)
    
    Please Note : 
    1. One important thing to know about array slices is that they return views rather than copies of the array
       data. (i.e. If the value of a slice is set, the original array is modified too)

In [126]:
# Array Slicing on a One-dimensional array
print(f"\n {one_dim_array}")

# Slices first 3 elements
print(f'\nSliced array of First 3 elements : {one_dim_array[:3]}')

# Slices last 4 elements
print(f'\nSliced array of Last 4 elements : {one_dim_array[3:]}')

# Slices elements between 3 and 5 inclusive
print(f'\nSliced array of element 3 to 5 : {one_dim_array[2:5]}')

# Slices alternate elements
print(f'\nSliced array of alternate elements : {one_dim_array[::2]}')

# Slices alternate elements starting at index 1
print(f'\nSliced array of alternate elements starting at index 1 : {one_dim_array[1::2]}')

# Slices in reverse order
print(f'\nReversed array  : {one_dim_array[::-1]}')




 [ 4 11  8  8 49  5  2]

Sliced array of First 3 elements : [ 4 11  8]

Sliced array of Last 4 elements : [ 8 49  5  2]

Sliced array of element 3 to 5 : [ 8  8 49]

Sliced array of alternate elements : [ 4  8 49  2]

Sliced array of alternate elements starting at index 1 : [11  8  5]

Reversed array  : [ 2  5 49  8  8 11  4]


In [127]:
# Array Slicing on a Two-dimensional array
print(f"\n {two_dim_array}")

# Slices 2nd column from all rows
print(f'\nSliced array of elements from 2nd column from all rows: \n {two_dim_array[:,1:]}')

# Slices from 3rd row to 5th row of 1st column
print(f'\nSliced array of elements from 3rd row to 5th row of 1st column: \n{two_dim_array[2:5,:1]}')

# Slices alternate rows
print(f'\nSliced array of elements from alternate rows : \n {two_dim_array[::2,:]}')

# Slices alternate rows starting at index 1
print(f'\nSliced array of alternate elements starting at index 1 :\n {two_dim_array[1::2,:]}')

# Slices in reverse order
print(f'\nReversed array  : \n {two_dim_array[::-1,::-1]}')


 [['Cupcake' 'Donut']
 ['Eclair' 'Froyo']
 ['GingerBread Androi' 'Honeycomb']
 ['Ice Cream Sandwich' 'Jelly Bean']
 ['KitKat' 'Lollipop']
 ['Marshmallow' 'Nougat']
 ['Oreo' 'Pie']]

Sliced array of elements from 2nd column from all rows: 
 [['Donut']
 ['Froyo']
 ['Honeycomb']
 ['Jelly Bean']
 ['Lollipop']
 ['Nougat']
 ['Pie']]

Sliced array of elements from 3rd row to 5th row of 1st column: 
[['GingerBread Androi']
 ['Ice Cream Sandwich']
 ['KitKat']]

Sliced array of elements from alternate rows : 
 [['Cupcake' 'Donut']
 ['GingerBread Androi' 'Honeycomb']
 ['KitKat' 'Lollipop']
 ['Oreo' 'Pie']]

Sliced array of alternate elements starting at index 1 :
 [['Eclair' 'Froyo']
 ['Ice Cream Sandwich' 'Jelly Bean']
 ['Marshmallow' 'Nougat']]

Reversed array  : 
 [['Pie' 'Oreo']
 ['Nougat' 'Marshmallow']
 ['Lollipop' 'KitKat']
 ['Jelly Bean' 'Ice Cream Sandwich']
 ['Honeycomb' 'GingerBread Androi']
 ['Froyo' 'Eclair']
 ['Donut' 'Cupcake']]


In [128]:
# Array Slicing on a Three-dimensional array
print(f"\n {three_dim_array}")

# Slicing 2nd sheet, 2nd row and all columns 
print(f'\nSliced array of elements from 2nd sheet, 2nd row and all columns: \n {three_dim_array[1:2,1:,:]}')

# Negative index slicing
print(f'\nNegative indexing : Sliced array of elements from 2nd sheet, 2nd row and all columns: \n {three_dim_array[-2:-1,-1:,:]}')



 [[['Civic' 'Accord' 'Pilot' 'FR-V']
  ['Odyssey' 'Jazz' 'CR-V' 'NSX']]

 [['Insight' 'Ridgeline' 'Legend' 'HR-V']
  ['Passport' 'S660' 'Clarity' 'Mobilio']]

 [['Airwave' 'Avancier' 'Beat' 'Shuttle']
  ['Concerto' 'Element' 'Logo' 'Stream']]]

Sliced array of elements from 2nd sheet, 2nd row and all columns: 
 [[['Passport' 'S660' 'Clarity' 'Mobilio']]]

Negative indexing : Sliced array of elements from 2nd sheet, 2nd row and all columns: 
 [[['Passport' 'S660' 'Clarity' 'Mobilio']]]


> #### Creating Copies of Arrays

    However, it is useful to explicitly create a copy of data before it is modified. This can be done using copy()
    

In [132]:
# Creating a copy of slice of two-dimensional array
two_dim_slice = two_dim_array[3:,1:]
two_dim_slice[3,0] = "Pie Android"
print(two_dim_array)
# Note that changing sub array changed the original array; 
two_dim_slice

[['Cupcake' 'Donut']
 ['Eclair' 'Froyo']
 ['GingerBread Androi' 'Honeycomb']
 ['Ice Cream Sandwich' 'Jelly Bean']
 ['KitKat' 'Lollipop']
 ['Marshmallow' 'Nougat']
 ['Oreo' 'Pie Android']]


array([['Jelly Bean'],
       ['Lollipop'],
       ['Nougat'],
       ['Pie Android']], dtype='<U18')

In [133]:
# Creating a copy of slice of two-dimensional array
two_dim_slice = two_dim_array[3:,1:].copy()
two_dim_slice[3,0] = "PIE"
print(two_dim_array)

# Note that there is no change in the original array; If .copy() is not used it will change the original array
two_dim_slice

[['Cupcake' 'Donut']
 ['Eclair' 'Froyo']
 ['GingerBread Androi' 'Honeycomb']
 ['Ice Cream Sandwich' 'Jelly Bean']
 ['KitKat' 'Lollipop']
 ['Marshmallow' 'Nougat']
 ['Oreo' 'Pie Android']]


array([['Jelly Bean'],
       ['Lollipop'],
       ['Nougat'],
       ['PIE']], dtype='<U18')

> #### Reshaping Arrays

      Another useful utility on arrays is reshaping of arrays. Reshaping an array might refer to any operation 
      that might change the shape of the original array.
      
      We shall discuss the following reshaping techniques in this section:
        
        1. Using reshape()
        2. Transposing arrays
        3. Swapping Axes of arrays
        4. Raveling/Flattening
      
     
      Please Note :
      
      1. One of the passed shape dimensions can be –1, in which case the value used for that dimension will be 
      inferred from the data. (i.e. if the size is 16 and we passed only 2; the other one has to be 8)
      2. One of the most common patterns of reshaping is the conversion of 1D array to a 2D row or a column matrix. 
      3. Its important to note that, a no-copy view of the initial array will be used by Reshape() whenever 
      possible, but with noncontiguous memory buffers this is not always the case.    



> **Using .reshape()**

In [45]:
# Reshape() reshapes the array, provided, the size of initial array matches the reshaped array
reshaped_arr = np.arange(1,15).reshape((2,7))
reshaped_arr 

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [46]:
# If one of the passed shape dimensions is -1, the value is inferred from the data passed
np.arange(14).reshape(7,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [47]:
# We can also pass shape of another array to reshape an array
np.arange(14).reshape(reshaped_arr.shape)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [48]:
# Reshape() for converting 1D array to 2D 
arr_reshape = np.array(['alpha','beta','gamma'])

# Here, we are converting a 1D array to a 2D row
arr_reshape[np.newaxis,:] # is same as
arr_reshape.reshape(1,3)

# Here, we are converting a 1D array to a column matrix
arr_reshape[:,np.newaxis] # is same as
arr_reshape.reshape(3,1)

array([['alpha'],
       ['beta'],
       ['gamma']], dtype='<U5')

>**Reshaping Arrays : Transpose and Axes Swapping**

In [49]:
# Transposing the array
reshaped_arr.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

>**Axes Swapping**

In [135]:
# For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes
three_dim_array.transpose((1,2,0))

array([[['Civic', 'Insight', 'Fit'],
        ['Accord', 'Ridgeline', 'Avancier'],
        ['Pilot', 'Legend', 'Beat'],
        ['FR-V', 'HR-V', 'Shuttle']],

       [['Odyssey', 'Passport', 'Concerto'],
        ['Jazz', 'S660', 'Element'],
        ['CR-V', 'Clarity', 'Logo'],
        ['NSX', 'Mobilio', 'Stream']]], dtype='<U9')

>#### Raveling / Flattening 

    This operation is opposite to reshaping and it collapses the structure of array to give a flattened array.
    There are mainly 2 methods: ravel() and flatten()
    
    ravel does not produce a copy of the underlying values if the values in the result were contiguous in the 
    original array.
    
    The flatten method behaves like ravel except it always returns a copy of the data:
    
    Please Note : 
    1. The reshape() and ravel() accept an optional argument of order that can be 'C'/'F' which stands
    for 'Row Major'/'Column Major' respectively.
    2. C/'Row Major' : Traverse higher dimensions first (e.g., axis 1 before advancing on axis 0).
    3. Fortran/'Column Major' : Traverse higher dimensions last (e.g., axis 0 before advancing on axis 1).




In [137]:
# Raveling an array with order 'F'
three_dim_array.ravel('F')

array(['Civic', 'Insight', 'Fit', 'Odyssey', 'Passport', 'Concerto',
       'Accord', 'Ridgeline', 'Avancier', 'Jazz', 'S660', 'Element',
       'Pilot', 'Legend', 'Beat', 'CR-V', 'Clarity', 'Logo', 'FR-V',
       'HR-V', 'Shuttle', 'NSX', 'Mobilio', 'Stream'], dtype='<U9')

In [136]:
# Flattening an array with default order 'C'
three_dim_array.flatten()

array(['Civic', 'Accord', 'Pilot', 'FR-V', 'Odyssey', 'Jazz', 'CR-V',
       'NSX', 'Insight', 'Ridgeline', 'Legend', 'HR-V', 'Passport',
       'S660', 'Clarity', 'Mobilio', 'Fit', 'Avancier', 'Beat', 'Shuttle',
       'Concerto', 'Element', 'Logo', 'Stream'], dtype='<U9')

> **Concatenating Arrays**

    Concatenation, or joining of two arrays in NumPy is achieved by np.concatenate(), np.hstack() and np.vstack()

    Please Note : 
    
    1. np.concatenate : One important aspect to note is that, all the input arrays must have same number of 
       dimensions.
    2. For concatenating arrays of mixed dimensions, we use np.vstack, np.hstack and np.dstack.

In [54]:
# np.concatenate : Concatenating 1D arrays
print("Concatenating one dimensional array : {}".format(np.concatenate([['delta','epsilon'],['zeta']])))

# np.concatenate : Concatenating multidimensional arrays
two_dim_concat_x = [[' alpha','beta','gamma'],
                    ['delta','epsilon','zeta']]
two_dim_concat_y = [['eta','theta','iota'],
                   ['kappa','lambda','mu']]

print("\nConcatenating two dimensional array : \n{}"
      .format(np.concatenate([two_dim_concat_x,two_dim_concat_y])))

print("\nConcatenating two dimensional array along the vertical axis : \n{}"
      .format(np.concatenate([two_dim_concat_x,two_dim_concat_y],axis=1)))


Concatenating one dimensional array : ['delta' 'epsilon' 'zeta']

Concatenating two dimensional array : 
[[' alpha' 'beta' 'gamma']
 ['delta' 'epsilon' 'zeta']
 ['eta' 'theta' 'iota']
 ['kappa' 'lambda' 'mu']]

Concatenating two dimensional array along the vertical axis : 
[[' alpha' 'beta' 'gamma' 'eta' 'theta' 'iota']
 ['delta' 'epsilon' 'zeta' 'kappa' 'lambda' 'mu']]


In [55]:
# Concatenating mixed dimensional arrays with vstack
print("\nConcatenating mixed dimensional array using vstack : \n{}".format(np.vstack([['nu','zi','omicron'],two_dim_concat_y])))

# Concatenating mixed dimensional arrays with hstack
print("\nConcatenating mixed dimensional array using hstack : \n{}".format(np.hstack([[['pi'],
                                                                                       ['rho']],two_dim_concat_x])))


Concatenating mixed dimensional array using vstack : 
[['nu' 'zi' 'omicron']
 ['eta' 'theta' 'iota']
 ['kappa' 'lambda' 'mu']]

Concatenating mixed dimensional array using hstack : 
[['pi' ' alpha' 'beta' 'gamma']
 ['rho' 'delta' 'epsilon' 'zeta']]


> **Splitting Arrays**

    Splitting an array in NumPy is implemented by functions np.split, np.hsplit, np.vsplit and np.dsplit.
    Input to this function is the array to be split and the list of split points.

In [139]:
# Consider this (2,3,4) array for splitting
array_split = np.array([[["Hydrogen","Helium","Lithium","Beryllium"],
                         ["Boron","Carbon","Nitrogen","Oxygen"],
                         ["Flourine","Neon","Sodium","Magnesium"]],
                        [["Aluminium","Silicon","Phosphorus","Sulfur"],
                         ["Chlorine","Argon","Potassium","Calcium"],
                         ["Scandium","Titanium","Vanadium","Chromium"]]])

array_split

array([[['Hydrogen', 'Helium', 'Lithium', 'Beryllium'],
        ['Boron', 'Carbon', 'Nitrogen', 'Oxygen'],
        ['Flourine', 'Neon', 'Sodium', 'Magnesium']],

       [['Aluminium', 'Silicon', 'Phosphorus', 'Sulfur'],
        ['Chlorine', 'Argon', 'Potassium', 'Calcium'],
        ['Scandium', 'Titanium', 'Vanadium', 'Chromium']]], dtype='<U10')

In [145]:
# vsplit splits at axis 0 at point 1
split_piece_1,split_piece_2 = np.vsplit(array_split,[1])

print(f'Split Piece 1 :\n\n {split_piece_1}')
print("\n")
print(f'Split Piece 2 :\n\n {split_piece_2}')

Split Piece 1 :

 [[['Hydrogen' 'Helium' 'Lithium' 'Beryllium']
  ['Boron' 'Carbon' 'Nitrogen' 'Oxygen']
  ['Flourine' 'Neon' 'Sodium' 'Magnesium']]]


Split Piece 2 :

 [[['Aluminium' 'Silicon' 'Phosphorus' 'Sulfur']
  ['Chlorine' 'Argon' 'Potassium' 'Calcium']
  ['Scandium' 'Titanium' 'Vanadium' 'Chromium']]]


In [146]:
# hsplit splits at axis 1 at point 1
split_piece_3,split_piece_4 = np.hsplit(array_split,[1])

print(f'Split Piece 3 :\n\n {split_piece_3}')
print("\n")
print(f'Split Piece 4 :\n\n {split_piece_4}')

Split Piece 3 :

 [[['Hydrogen' 'Helium' 'Lithium' 'Beryllium']]

 [['Aluminium' 'Silicon' 'Phosphorus' 'Sulfur']]]


Split Piece 4 :

 [[['Boron' 'Carbon' 'Nitrogen' 'Oxygen']
  ['Flourine' 'Neon' 'Sodium' 'Magnesium']]

 [['Chlorine' 'Argon' 'Potassium' 'Calcium']
  ['Scandium' 'Titanium' 'Vanadium' 'Chromium']]]


In [147]:
# dsplit splits at axis 2
split_piece_5,split_piece_6,split_piece_7 = np.dsplit(array_split,[1,2])

print(f'Split Piece 5 :\n\n {split_piece_5}')
print("\n")
print(f'Split Piece 6 :\n\n {split_piece_6}')
print("\n")
print(f'Split Piece 7 :\n\n {split_piece_7}')

Split Piece 5 :

 [[['Hydrogen']
  ['Boron']
  ['Flourine']]

 [['Aluminium']
  ['Chlorine']
  ['Scandium']]]


Split Piece 6 :

 [[['Helium']
  ['Carbon']
  ['Neon']]

 [['Silicon']
  ['Argon']
  ['Titanium']]]


Split Piece 7 :

 [[['Lithium' 'Beryllium']
  ['Nitrogen' 'Oxygen']
  ['Sodium' 'Magnesium']]

 [['Phosphorus' 'Sulfur']
  ['Potassium' 'Calcium']
  ['Vanadium' 'Chromium']]]


> #### Repeating Elements : repeat and tile methods

    Repeating refers to repeating individual elements and tile method repeats the array as blocks.
    
    Please Note :
    1. If axis is omitted for a repeat method on multidimensional array, the array is flattened.
    2. 
    

In [61]:
arr_rep = np.arange(4)
print(f"Original Array :{arr_rep}")

# .repeat() by passing an array
print(f"Repeated Array using an array as input :{arr_rep.repeat([2,3,4,5])}")

# .repeat() by passing integer input
print(f"Repeated Array using an integer as input :{arr_rep.repeat(2)}")

Original Array :[0 1 2 3]
Repeated Array using an array as input :[0 0 1 1 1 2 2 2 2 3 3 3 3 3]
Repeated Array using an integer as input :[0 0 1 1 2 2 3 3]


In [150]:
arr_rep_multidim =np.random.randn(3,2,2)
print(f'Original array: \n {arr_rep_multidim}')
# If axis is omitted for a repeat method on multidimensional array, the array is flattened
print(f'\nIf axis argument is omitted for a multidim array : \n{arr_rep_multidim.repeat(2)}')

# The array can be repeated in any axis
arr_rep_multidim.repeat(2,axis=2)

Original array: 
 [[[-0.2002186   0.02174383]
  [-0.21563199  0.74020422]]

 [[ 0.33666958 -0.73115436]
  [-0.49748933  0.08560858]]

 [[ 0.15859387  1.2265962 ]
  [ 0.45002649  1.101066  ]]]

If axis argument is omitted for a multidim array : 
[-0.2002186  -0.2002186   0.02174383  0.02174383 -0.21563199 -0.21563199
  0.74020422  0.74020422  0.33666958  0.33666958 -0.73115436 -0.73115436
 -0.49748933 -0.49748933  0.08560858  0.08560858  0.15859387  0.15859387
  1.2265962   1.2265962   0.45002649  0.45002649  1.101066    1.101066  ]


array([[[-0.2002186 , -0.2002186 ,  0.02174383,  0.02174383],
        [-0.21563199, -0.21563199,  0.74020422,  0.74020422]],

       [[ 0.33666958,  0.33666958, -0.73115436, -0.73115436],
        [-0.49748933, -0.49748933,  0.08560858,  0.08560858]],

       [[ 0.15859387,  0.15859387,  1.2265962 ,  1.2265962 ],
        [ 0.45002649,  0.45002649,  1.101066  ,  1.101066  ]]])

In [63]:
# tile() for a one dimensional array
np.tile(arr_rep,3)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [157]:
# tile() for a multi-dimensional array stacks the tiles along the axis mentioned 
np.tile(arr_rep_multidim,(2,1))

array([[[-0.2002186 ,  0.02174383],
        [-0.21563199,  0.74020422],
        [-0.2002186 ,  0.02174383],
        [-0.21563199,  0.74020422]],

       [[ 0.33666958, -0.73115436],
        [-0.49748933,  0.08560858],
        [ 0.33666958, -0.73115436],
        [-0.49748933,  0.08560858]],

       [[ 0.15859387,  1.2265962 ],
        [ 0.45002649,  1.101066  ],
        [ 0.15859387,  1.2265962 ],
        [ 0.45002649,  1.101066  ]]])