### <center>Numpy Vectorized Computations</center>

> **Numpy Vectorized Computations**
        
    This notebook introduces concepts of vectorization, implemented through NumPy’s universal functions that 
    enables NumPy to make repeated calculations on array elements much more efficient.UFuncs perform Element-Wise 
    operations on  data in ndarrays.Its important to note that UFuncs can return multiple arrays (E.g. divmod), 
    although less frequently used.
        
    Additionally, it also accepts an optional "out" argument that allows them to operate in-place on arrays.
    Vectorized operations in NumPy can be broadly classified as: 
    
        Unary ufuncs
        Binary ufuncs   
    
    The topics covered in this notebook are as follows:
    
    1. Unary UFuncs  
    2. Unary UFuncs for NaN
    3. Binary UFuncs
        - Mathematical Operators
        - Comparison Operators
        - Boolean Operators
            > np.non_zero : Counting Entries
        - ufunc methods
    4. Broadcasting

In [47]:
# Importing numpy library
import numpy as np

In [48]:
# Creating a floating point ndarray to demonstrate UFuncs
arr_ufuncs_float = np.random.randn(2,2,3)
print("Floating point ndarray :\n{}".format(arr_ufuncs_float))

# Creating an integer ndarray to demonstrate UFuncs
arr_ufuncs_int = np.random.randint(-12,14,size=(2,2,3))
print("\nInteger ndarray :\n{}".format(arr_ufuncs_int))

Floating point ndarray :
[[[-1.23911629 -0.33523566  0.52726431]
  [-0.71893874  1.19092479  1.42764725]]

 [[ 0.49832967  1.24040982  0.47268116]
  [-0.57040815 -1.01906352 -0.47143276]]]

Integer ndarray :
[[[ 3 -2  5]
  [ 7  8  9]]

 [[11  5 -7]
  [12 -5  9]]]


### <center>Unary UFuncs</center>

    We shall discuss the following Unary ufuncs in this section:
    
     - abs  
     - fabs
     - sqrt
     - square
     - exp
     - log,log10,log2,logp
     - sign
     - ceil
     - floor
     - rint
     - modf
     - isnan
     - isfinite,isinf
     - cos,cosh,sin,sinh,tan,tanh
     - arccos,arccosh,arcsin,arcsinh,arctan,arctanh
     - logical_not

In [49]:
# Computes the absolute value of a floating point array
np.fabs(arr_ufuncs_float)

array([[[1.23911629, 0.33523566, 0.52726431],
        [0.71893874, 1.19092479, 1.42764725]],

       [[0.49832967, 1.24040982, 0.47268116],
        [0.57040815, 1.01906352, 0.47143276]]])

In [50]:
# Computes the absolute value of an integer array
np.abs(arr_ufuncs_int)

array([[[ 3,  2,  5],
        [ 7,  8,  9]],

       [[11,  5,  7],
        [12,  5,  9]]])

In [51]:
# Computes the Square root of the elements
np.sqrt(np.abs((arr_ufuncs_int)))

array([[[1.73205081, 1.41421356, 2.23606798],
        [2.64575131, 2.82842712, 3.        ]],

       [[3.31662479, 2.23606798, 2.64575131],
        [3.46410162, 2.23606798, 3.        ]]])

In [52]:
# Computes the square
np.square(arr_ufuncs_float)

array([[[1.53540918, 0.11238295, 0.27800765],
        [0.51687291, 1.41830185, 2.03817667]],

       [[0.24833246, 1.53861652, 0.22342748],
        [0.32536546, 1.03849045, 0.22224885]]])

In [53]:
# Computes the exponent e^x of the array elements
np.exp(arr_ufuncs_float)

array([[[0.28964006, 0.71516953, 1.6942909 ],
        [0.4872691 , 3.29012247, 4.16887931]],

       [[1.64596967, 3.45702993, 1.60428978],
        [0.56529466, 0.36093279, 0.62410743]]])

In [54]:
# Computes log to the base e of array elements
np.log(np.abs(arr_ufuncs_float))

# Similarly log10, log2, logp computes the logarithm to the base 10, base 2 and log(1+x) respectively

array([[[ 0.21439846, -1.09292153, -0.64005333],
        [-0.32997913,  0.17473014,  0.35602781]],

       [[-0.69649342,  0.21544182, -0.74933421],
        [-0.56140312,  0.01888409, -0.7519788 ]]])

In [55]:
# Computes the sign of array elements; 1 for positive, 0 for zero and -1 for Negative
np.sign(arr_ufuncs_int)

array([[[ 1, -1,  1],
        [ 1,  1,  1]],

       [[ 1,  1, -1],
        [ 1, -1,  1]]])

In [56]:
# Computes the ceiling for each element; Smallest integer greater than or equal to that number
np.ceil(arr_ufuncs_float)

array([[[-1., -0.,  1.],
        [-0.,  2.,  2.]],

       [[ 1.,  2.,  1.],
        [-0., -1., -0.]]])

In [57]:
# Computes the floor for each element; Largest integer greater than or equal to that number
np.floor(arr_ufuncs_float)

array([[[-2., -1.,  0.],
        [-1.,  1.,  1.]],

       [[ 0.,  1.,  0.],
        [-1., -2., -1.]]])

In [58]:
# Rounds the element to nearest integer ; preserves the dtype of the initial array
np.round(arr_ufuncs_float)

array([[[-1., -0.,  1.],
        [-1.,  1.,  1.]],

       [[ 0.,  1.,  0.],
        [-1., -1., -0.]]])

In [59]:
# Returns fraction and integral part as a separate array
fraction, integral = np.modf(arr_ufuncs_float)

print (f'Integral Part = \n {integral}')

print (f'\nFraction Part = \n {fraction}')

Integral Part = 
 [[[-1. -0.  0.]
  [-0.  1.  1.]]

 [[ 0.  1.  0.]
  [-0. -1. -0.]]]

Fraction Part = 
 [[[-0.23911629 -0.33523566  0.52726431]
  [-0.71893874  0.19092479  0.42764725]]

 [[ 0.49832967  0.24040982  0.47268116]
  [-0.57040815 -0.01906352 -0.47143276]]]


In [60]:
# Inverse trigonometric functions: arccos,arccosh,arcsin,arcsinh,arctan,arctanh
np.arctan(arr_ufuncs_float)

array([[[-0.89178544, -0.32346167,  0.4852204 ],
        [-0.62332377,  0.87232204,  0.95976631]],

       [[ 0.46231046,  0.8922953 ,  0.44155467],
        [-0.51837654, -0.79483965, -0.44053377]]])

In [61]:
# Regular and hyperbolic trigonometric functions: cos,cosh,sin,sinh,tan,tanh
np.cos(arr_ufuncs_int)

array([[[-0.9899925 , -0.41614684,  0.28366219],
        [ 0.75390225, -0.14550003, -0.91113026]],

       [[ 0.0044257 ,  0.28366219,  0.75390225],
        [ 0.84385396,  0.28366219, -0.91113026]]])

In [62]:
# Compute truth value of not of x; 
np.logical_not(arr_ufuncs_int)

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

### <center>Unary UFuncs for Not a Number</center>

    In addition to dtype objects, NumPy introduces special numeric values: nan and inf. 
    These can arise in mathematical computations. 
    
        NOT A NUMBER(nan) : It indicates a value that should be numeric is, in fact, not defined mathematically. 
    For example, 0/0 yields nan. 
    Sometimes, nan is also used to signify missing information; for example, pandas uses this.
    
    isnan, isfinite, isinf

    Please Note : 
    1. Nothing is ever equal to nan; it makes no sense for something undefined to be equal to something else.
        Therefore, we need to use the NumPy function isnan to identify nan
    2. NAN,NaN and nan : All of them mean the same, Not a Number
    3. While the == sign does not work for nan, it does work for inf

In [63]:
# Creating An array consisting of nan and inf values
arr_ufuncs_naninf = np.array([[np.inf,np.nan,np.NaN],
                              [np.NAN,33,0],
                              [5/np.inf,np.inf*np.nan,np.inf/np.inf]])
arr_ufuncs_naninf

array([[inf, nan, nan],
       [nan, 33.,  0.],
       [ 0., nan, nan]])

In [64]:
# Return boolean array indicating whether each value is NaN
np.isnan(arr_ufuncs_naninf)

array([[False,  True,  True],
       [ True, False, False],
       [False,  True,  True]])

In [65]:
# Return boolean array indicating whether each element is finite 
np.isfinite(arr_ufuncs_naninf)

array([[False, False, False],
       [False,  True,  True],
       [ True, False, False]])

In [66]:
# Returns boolean array indicating whether each element is infinite
np.isinf(arr_ufuncs_naninf)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [67]:
print("nan==nan ? {}".format(np.nan==np.nan))
print("inf==inf ? {}".format(np.inf==np.inf))

nan==nan ? False
inf==inf ? True


### <center>Binary UFuncs</center>

> **Binary UFuncs : Mathematical Operators**

        We shall discuss the following Binary ufuncs in this section:

      - add
      - subtract
      - multiply
      - divide
      - floor_divide
      - power
      - maximum,fmax
      - minimum,fmin
      - mod
      - copysign
      - greater, greater_equal, less, less_equal, equal, not_equal
      - logical_and, logical_or, logical_xor
       

In [68]:
# Adds corresponding elements in the input arrays
np.add(arr_ufuncs_int,arr_ufuncs_int*2)

array([[[  9,  -6,  15],
        [ 21,  24,  27]],

       [[ 33,  15, -21],
        [ 36, -15,  27]]])

In [69]:
# Subtracts corresponding elements in the input arrays
np.subtract(arr_ufuncs_int,arr_ufuncs_int*5)

array([[[-12,   8, -20],
        [-28, -32, -36]],

       [[-44, -20,  28],
        [-48,  20, -36]]])

In [70]:
# Multiplies corresponding elements in the input arrays 
np.multiply(arr_ufuncs_int,arr_ufuncs_int*2)

array([[[ 18,   8,  50],
        [ 98, 128, 162]],

       [[242,  50,  98],
        [288,  50, 162]]])

In [71]:
# Divides corresponding elements in the input arrays
np.divide(arr_ufuncs_int,arr_ufuncs_float)

array([[[ -2.42108027,   5.96595243,   9.48291006],
        [ -9.73657371,   6.71746871,   6.30407827]],

       [[ 22.07374068,   4.03092585, -14.80913701],
        [-21.03756744,   4.9064655 , -19.09073956]]])

In [72]:
# Floor divide truncates the remainder
np.floor_divide(arr_ufuncs_int,arr_ufuncs_float)

array([[[ -3.,   5.,   9.],
        [-10.,   6.,   6.]],

       [[ 22.,   4., -15.],
        [-22.,   4., -20.]]])

In [73]:
# Raises first array  to the power of second array
np.power(arr_ufuncs_float,arr_ufuncs_int)

array([[[-1.90255052e+00,  8.89814710e+00,  4.07513371e-02],
        [-9.92757526e-02,  4.04645467e+00,  2.46370223e+01]],

       [[ 4.70635017e-04,  2.93647275e+00,  1.89680191e+02],
        [ 1.18639334e-03, -9.09900131e-01, -1.15021177e-03]]])

In [74]:
# Maximum of the elements in the array element-wise; np.fmax ignores nan
np.maximum(arr_ufuncs_float,arr_ufuncs_int)

array([[[ 3.        , -0.33523566,  5.        ],
        [ 7.        ,  8.        ,  9.        ]],

       [[11.        ,  5.        ,  0.47268116],
        [12.        , -1.01906352,  9.        ]]])

In [75]:
# Minimum of the elements in the array element-wise; np.fmin ignores nan
np.minimum(arr_ufuncs_int,arr_ufuncs_float)

array([[[-1.23911629, -2.        ,  0.52726431],
        [-0.71893874,  1.19092479,  1.42764725]],

       [[ 0.49832967,  1.24040982, -7.        ],
        [-0.57040815, -5.        , -0.47143276]]])

In [76]:
# Remainder of division element-wise
np.mod(arr_ufuncs_int,arr_ufuncs_float)

array([[[-0.71734887, -0.3238217 ,  0.25462124],
        [-0.18938736,  0.85445127,  0.4341165 ]],

       [[ 0.03674717,  0.03836073,  0.09021734],
        [-0.54897938, -0.92374593, -0.42865516]]])

In [77]:
# Copies the sign of second array to the first array
np.copysign(arr_ufuncs_int,arr_ufuncs_float)

array([[[ -3.,  -2.,   5.],
        [ -7.,   8.,   9.]],

       [[ 11.,   5.,   7.],
        [-12.,  -5.,  -9.]]])

In [78]:
# logical_and, logical_or, logical_xor : Computes element-wise truth value of logical operations of and, or , xor
np.logical_or(arr_ufuncs_int,arr_ufuncs_int)

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

> **Binary UFuncs : Comparison Operators** 

    Since these operators always result in a boolean array, we can use these ufuncs to do element-wise comparisons over arrays.
    
    We can use the comparison operators or their equivalent ufunc for accomplishing the task.
    For instance, Operator "==" is same as "np.equal".
    A summary of comparison operators and their equivalent ufunc is shown below:
    
        Operator   |   UFunc
       ------------|-------------------  
           ==      |   np.equal
           !=      |   np.not_equal
           <       |   np.less
           <=      |   np.less_equal
           >       |   np.greater  
           >=      |   np.greater_equal

In [79]:
# Element comparison yielding a boolean array: equal
np.equal(arr_ufuncs_int,arr_ufuncs_int)

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [80]:
# Element-wise comparison to find the elements less than a particular value
arr_ufuncs_int<8 
# is same as
np.less(arr_ufuncs_int,8)

array([[[ True,  True,  True],
        [ True, False, False]],

       [[False,  True,  True],
        [False,  True, False]]])

> **Binary UFuncs : Boolean Operators**
    
        Boolean Operators can accomplish a variety of compound tasks on arrays.
    (Lets consider the dataframe consisting of banks that closed between 2000 and 2019.To evaluate compound 
    questions, such as, How many banks closed in 2008 in California? 
        This is accomplished by Boolean Operators. Below is a list of UFuncs for Boolean operators and their 
    corresponding boolean operators.
    
    bitwise_and (&)
    bitwise_or (|)
    bitwise_xor (^)
    bitwise_not (~)
    
    Please Note : 
    1. Combining Boolean Operators with Comparison operators on arrays can lead to a wide range of efficient  
    logical operations

> **Binary UFuncs : ufunc methods**

      All binary ufuncs support four methods for performing specialized functions.
      Each of the five methods will be discussed below.

        reduce       : Aggregates values by applying ufunc along the mentioned axis 
        accumulate   : Accumulates values, preserving all partial aggregates.
        reduceat     : Performs a (local) reduce with specified slices over a single axis to produce an aggregate 
                       array
        outer        : Apply ufunc to all pairs of elements in x and y; the resulting array has shape 
                       x.shape + y.shape
        at           : performs unbuffered in place operation on array for elements specified by 'indices'

In [81]:
# Multidimensional Array creation
arr_ufunc_meth = np.random.randint(9,size=(3,4,5))
arr_ufunc_meth

array([[[1, 8, 4, 5, 8],
        [5, 4, 5, 5, 4],
        [7, 5, 0, 6, 6],
        [5, 6, 1, 8, 4]],

       [[7, 3, 1, 5, 6],
        [4, 5, 8, 7, 5],
        [2, 8, 6, 0, 6],
        [7, 5, 7, 8, 4]],

       [[6, 6, 5, 4, 2],
        [6, 5, 0, 2, 3],
        [8, 7, 6, 0, 1],
        [1, 0, 7, 3, 1]]])

In [82]:
# reduce with axis input applies ufunc and reduces the mentioned axis to single element
np.add.reduce(arr_ufunc_meth,axis = 2)

array([[26, 23, 24, 24],
       [22, 29, 22, 31],
       [23, 16, 22, 12]])

In [83]:
# accumulate with axis input applies the unfunc and gives intermediate results of reduction
np.add.accumulate(arr_ufunc_meth,axis=2)

array([[[ 1,  9, 13, 18, 26],
        [ 5,  9, 14, 19, 23],
        [ 7, 12, 12, 18, 24],
        [ 5, 11, 12, 20, 24]],

       [[ 7, 10, 11, 16, 22],
        [ 4,  9, 17, 24, 29],
        [ 2, 10, 16, 16, 22],
        [ 7, 12, 19, 27, 31]],

       [[ 6, 12, 17, 21, 23],
        [ 6, 11, 11, 13, 16],
        [ 8, 15, 21, 21, 22],
        [ 1,  1,  8, 11, 12]]])

In [84]:
# reduceat performs a local groupby on the 2nd argument (i.e. binedges input) of the axis mentioned
# In the below example, it splits the axis to 3 sections; (i.e. 0:2 , 2:4 , 4+); outerbound exclusive
print(np.add.reduceat(arr_ufunc_meth,[0,2,4],axis=2))


[[[ 9  9  8]
  [ 9 10  4]
  [12  6  6]
  [11  9  4]]

 [[10  6  6]
  [ 9 15  5]
  [10  6  6]
  [12 15  4]]

 [[12  9  2]
  [11  2  3]
  [15  6  1]
  [ 1 10  1]]]


In [85]:
# outer performs a pairwise cross-product between two arrays:
array_outer_1 = np.random.randint(10,size=(2,3))
array_outer_2 = np.random.randint(15,size=(2,3))
print(f'Array 1 : \n{array_outer_1}')
print(f'\nArray 2 : \n{array_outer_2}')

np.add.outer(array_outer_1,array_outer_2)

Array 1 : 
[[8 1 7]
 [3 2 3]]

Array 2 : 
[[ 8  7 14]
 [10  3  8]]


array([[[[16, 15, 22],
         [18, 11, 16]],

        [[ 9,  8, 15],
         [11,  4,  9]],

        [[15, 14, 21],
         [17, 10, 15]]],


       [[[11, 10, 17],
         [13,  6, 11]],

        [[10,  9, 16],
         [12,  5, 10]],

        [[11, 10, 17],
         [13,  6, 11]]]])

In [86]:
# at performs unbuffered in place operation on array for elements specified by 'indices'.
arr_ufunc_at = np.random.randint(10,size=(3,2,4))
print(f"Original Array :\n{arr_ufunc_at}")

# This statement performs a in-place increment of the corner elements by 10
np.add.at(arr_ufunc_at,tuple([[[0, 0],
                               [2, 2]], 
                              [[0, 0], 
                               [1, 1]], 
                              [[0, 3], 
                               [0, 3]]]),10)

print(f"\nIncremented Array :\n{arr_ufunc_at}")

Original Array :
[[[4 1 0 5]
  [4 0 4 1]]

 [[4 5 6 5]
  [1 1 5 7]]

 [[7 2 2 8]
  [0 4 0 1]]]

Incremented Array :
[[[14  1  0 15]
  [ 4  0  4  1]]

 [[ 4  5  6  5]
  [ 1  1  5  7]]

 [[ 7  2  2  8]
  [10  4  0 11]]]


### <center>Broadcasting</center>

    Broadcasting is a set of rules for applying binary UFuncs on arrays of different sizes.
    
    Rules of Broadcasting : 
    
    1. Rule 1 : If the 2 arrays differ in dimensions, the shape of the one with fewer dimensions is padded with 1s on its leading side
    2. Rule 2 : If the shape of the 2 arrays does not match in any dimension, tha array with shape equal to 1 is stretched to match the other shape
    3. Rule 3 : If neither sizes match in any dimension nor is 1, then an error is raised

In [87]:
# Consider an array with dimensions (2,4,2,1)
arr_brd_1 = np.random.randint(40,size=(2,4,2,1))
arr_brd_1

array([[[[ 0],
         [22]],

        [[ 5],
         [25]],

        [[14],
         [30]],

        [[17],
         [32]]],


       [[[ 7],
         [14]],

        [[ 8],
         [10]],

        [[38],
         [ 9]],

        [[ 1],
         [20]]]])

In [88]:
# Consider another array with dimensions (2,3)
arr_brd_2 = np.random.randint(20,size=(2,3))

    In the above example : 
    Rule 1 : Since arr_brd_2 has fewer dimensions, its padded with 1s on left making its dimensions (1,1,2,3)
    Rule 2 : Since dimensions dont match, both arr_brd_1 and arr_brd_2 is stretched/broadcasted to form a output array of dimensions (2,4,2,3)
    
    Therefore, Broadcasting is viable.

In [89]:
arr_brd_1 + arr_brd_2

array([[[[12,  6, 17],
         [29, 22, 30]],

        [[17, 11, 22],
         [32, 25, 33]],

        [[26, 20, 31],
         [37, 30, 38]],

        [[29, 23, 34],
         [39, 32, 40]]],


       [[[19, 13, 24],
         [21, 14, 22]],

        [[20, 14, 25],
         [17, 10, 18]],

        [[50, 44, 55],
         [16,  9, 17]],

        [[13,  7, 18],
         [27, 20, 28]]]])

In [90]:
# Consider another array with dimensions (2,3,5)
arr_brd_3 = np.random.randint(20,size=(2,3,5))

In [91]:
# Because the arrays defy Rule 2, it cannot be broadcast to apply any binary ufunc
arr_brd_1+arr_brd_3

ValueError: operands could not be broadcast together with shapes (2,4,2,1) (2,3,5) 